/* create a database for iran khodro */
DROP DATABASE IF EXISTS Iran_Khodro;
CREATE DATABASE IF NOT EXISTS Iran_Khodro;
USE Iran_Khodro;

/* Refreshing database just for test - comment if not needed */
DROP TABLE IF EXISTS Cars;
DROP TABLE IF EXISTS Gears;
DROP TABLE IF EXISTS Colors;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Models;
DROP TABLE IF EXISTS Brands;
DROP TABLE IF EXISTS Suppliers;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Purchases;

/* Create databases */

/* GEAR */
CREATE TABLE IF NOT EXISTS Gears
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(255) NOT NULL
);

/* COLORS */
CREATE TABLE IF NOT EXISTS Colors
(
    NAME VARCHAR(255) NOT NULL PRIMARY KEY,
    CODE VARCHAR(255) NOT NULL
);

/* BRAND */
CREATE TABLE IF NOT EXISTS Brands
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

/* MODELS */
CREATE TABLE IF NOT EXISTS Models
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL, 
    BRAND_ID INT,
    FOREIGN KEY (BRAND_ID) REFERENCES Brands(ID)
);

/* CARS */
CREATE TABLE IF NOT EXISTS Cars
(
    VIN INT CHECK(VIN > 1000) NOT NULL,
    BRAND_ID INT NOT NULL,
    MODEL_ID INT NOT NULL,
    COLOR_NAME VARCHAR(255) NOT NULL,
    GEAR_ID INT NOT NULL,
    PRIMARY KEY (VIN),
    FOREIGN KEY (BRAND_ID) REFERENCES Brands(ID),
    FOREIGN KEY (MODEL_ID) REFERENCES Models(ID),
    FOREIGN KEY (COLOR_NAME) REFERENCES Colors(NAME),
    FOREIGN KEY (GEAR_ID) REFERENCES Gears(ID)
);

/* CUSTOMERS */
/* FIRST = F, LAST = L */
CREATE TABLE IF NOT EXISTS Customers
(
    NN CHAR(10) NOT NULL,
    PHONE CHAR(11) NOT NULL UNIQUE,
    F_NAME VARCHAR(255) NOT NULL,
    L_NAME VARCHAR(255) NOT NULL,
    ADDRS_PROV VARCHAR(64) NOT NULL,
    ADDRS_CITY VARCHAR(64) NOT NULL,
    ADDRS_DETAIL VARCHAR(512) NOT NULL,
    PRIMARY KEY (NN)
);

/* SUPPLIERS */
/* CONTRACT BEGIN = CB */
/* CONTRACT END = CE */
/* YEAR = Y, MONTH = M, DAY = D */
CREATE TABLE IF NOT EXISTS Suppliers
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CEO_F_NAME VARCHAR(255) NOT NULL,
    CEO_L_NAME VARCHAR(255) NOT NULL,
    CBY INT CHECK(CBY > 2000) NOT NULL,
    CBM INT CHECK(CBM > 0 AND CBM < 13) NOT NULL,
    CBD INT CHECK(CBD > 0 AND CBD < 32) NOT NULL,
    CEY INT CHECK(CEY > CBY) NOT NULL,
    CEM INT CHECK(CEM > 0 AND CEM < 13) NOT NULL,
    CED INT CHECK(CED > 0 AND CED < 32) NOT NULL,
    ADDRS_PROV VARCHAR(64) NOT NULL,
    ADDRS_CITY VARCHAR(64) NOT NULL,
    ADDRS_DETAIL VARCHAR(512) NOT NULL
);

/* PRODUCTS */
/* UNIT PRICE = UP */
CREATE TABLE IF NOT EXISTS Products
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    S_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    STOCK INT CHECK(STOCK >= 0) NOT NULL,
    UP INT CHECK(UP > 0) NOT NULL,
    FOREIGN KEY (S_ID) REFERENCES Suppliers(ID)
);

/* PURCHASES */
/* PURCHASE CODES ARE IF SOME PRODUCTS HAVE BEEB BOUGHT TOGATHER */
/* C = CAR, P = PRODUCT (here can be a car or product) */
/* NUMBER IS COUNT OF PRODUCT */
CREATE TABLE IF NOT EXISTS Purchases
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODE CHAR(20) NOT NULL,
    P_ID INT NOT NULL,
    P_TYPE CHAR(1) CHECK(P_TYPE IN ('C', 'P')) NOT NULL,
    NUM INT CHECK(NUM > 0) NOT NULL,
    FOREIGN KEY (BUYER_ID) REFERENCES Customers(NN)
);

CREATE TABLE IF NOT EXISTS Code_Buyer
(
    CODE CHAR(20) NOT NULL,
    BUYER_ID CHAR(10) NOT NULL,
    PRIMARY KEY (CODE, BUYER_ID),
    FOREIGN KEY (BUYER_ID) REFERENCES Customers(NN),
    FOREIGN KEY (CODE) REFERENCES Purchases(CODE)
);
