/* SELECT RELATED DATABASE */
USE iran_khodro;

/* CREATE TRIGGER FOR STOCK */
CREATE TRIGGER non_zero_stock BEFORE UPDATE ON Products
FOR EACH ROW
BEGIN
    IF (new.STOCK < 1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOCK CANNOT BE EMPTY';
    END IF
END